### ISSUE TITLE
大佬，uperf不兼容了吗，感觉挺好用的

### ISSUE THREAD

**Issue by zhangde2333** [shadow3aaa/fas-rs#10]

**Comment by shadow3aaa** [comment]
不再兼容的原因如下:
uperfv3不开源，无法优雅地整合
uperf-patch实现丑陋
uperfv3已经太老了，很多新soc并没有配置支持
在fas内只是忽略uperf建议的频率的写入，uperf本身还在分析并且不断建议频率，相当于多增一个没用的开销

**Comment by shadow3aaa** [comment]
6e481645fc573b9ef7d246a2d411bfc4d2afd92a我在此commit中已经实现了一个极简版的uperf，如果还是有需求使用uperf可以考虑用此功能代替

**Comment by gusc2013C** [comment]
> [6e48164](https://github.com/shadow3aaa/fas-rs/commit/6e481645fc573b9ef7d246a2d411bfc4d2afd92a) 我在此commit中已经实现了一个极简版的uperf，如果还是有需求使用uperf可以考虑用此功能代替

请问最新版本是否已经将这部分移除了？

**Comment by shadow3aaa** [comment]
> > [6e48164](https://github.com/shadow3aaa/fas-rs/commit/6e481645fc573b9ef7d246a2d411bfc4d2afd92a) 我在此commit中已经实现了一个极简版的uperf，如果还是有需求使用uperf可以考虑用此功能代替
> 
> 请问最新版本是否已经将这部分移除了？

是的

**Comment by gusc2013C** [comment]
> > > [6e48164](https://github.com/shadow3aaa/fas-rs/commit/6e481645fc573b9ef7d246a2d411bfc4d2afd92a) 我在此commit中已经实现了一个极简版的uperf，如果还是有需求使用uperf可以考虑用此功能代替
> > 
> > 
> > 请问最新版本是否已经将这部分移除了？
> 
> 是的

请问一下移除这部分的原因？是因为这部分uperf的作用不明显吗？谢谢您！

**Comment by shadow3aaa** [comment]
> > > > [6e48164](https://github.com/shadow3aaa/fas-rs/commit/6e481645fc573b9ef7d246a2d411bfc4d2afd92a) 我在此commit中已经实现了一个极简版的uperf，如果还是有需求使用uperf可以考虑用此功能代替
> > > 
> > > 
> > > 请问最新版本是否已经将这部分移除了？
> > 
> > 
> > 是的
> 
> 请问一下移除这部分的原因？是因为这部分uperf的作用不明显吗？谢谢您！

uperf太过复杂，对新设备也没有优势

**Comment by DdogezD** [comment]
可以尝试 https://github.com/DdogezD/fas-rs-mod/，使用scene调度作为日用app调度
