### ISSUE TITLE
Is this ok? (Screenshot attached)

### ISSUE THREAD

**Issue by nimbold** [shadow3aaa/fas-rs#11]
(Sorry for typing in English)

Hello, first of all thanks a lot for your work!
I've been using your module for Genshin Impact and I think I'm seeing a difference in power consumption.
I added the package name to the "Game.toml" file and when I run the game, the log shows records.
I just wanna know, is it working with the power parameters being empty? Or Is it needed to type something in "power save" line? 

![Screenshot_20231229-064934_X-plore.png](https://github.com/shadow3aaa/fas-rs/assets/11913706/fdeb86e3-d294-4bb9-a68f-22cea0f1c450)

![Screenshot_20231229-064919_X-plore.png](https://github.com/shadow3aaa/fas-rs/assets/11913706/d5836b34-e14b-4ba0-bafc-a5d5a0728f8c)

**Comment by shadow3aaa** [comment]
那些是给fas-rs的四个模式使用的配置，之前那里有一些可以手动配置的项，目前没有，但是我还是把它留在那里，未来可能会有可以配置的项

**Comment by nimbold** [comment]
Thanks a lot for explaining!
非常感谢您的解释!
