### ISSUE TITLE
v1.6.0没有下载地址

### ISSUE THREAD

**Issue by CJYKK** [shadow3aaa/fas-rs#12]
Magisk检查到了模块更新，尝试自动安装失败
![Screenshot_2024-01-10-20-32-19-154_renot.xzr.y.r.jpg](https://github.com/shadow3aaa/fas-rs/assets/59359590/34a47c07-c469-4886-bf6d-de50939a0f31)
![IMG_20240110_203320.jpg](https://github.com/shadow3aaa/fas-rs/assets/59359590/c5d43a78-5796-48f5-a451-fcfdbc1c8f36)

排查后发现，update.json指向的是不存在的Release
![IMG_20240110_203245.jpg](https://github.com/shadow3aaa/fas-rs/assets/59359590/0e95b24a-f75a-4d84-b0ba-4ce07452f6e1)
![IMG_20240110_203412.jpg](https://github.com/shadow3aaa/fas-rs/assets/59359590/044ba6f0-dd67-4fd7-8768-54a0f8ad4774)

（Release中没有v1.6.0）
![Screenshot_2024-01-10-20-32-27-648_com.github.android.jpg](https://github.com/shadow3aaa/fas-rs/assets/59359590/0278b9d6-f279-403d-8f12-3b4e53fced29)

请问是不是忘记发了？

**Comment by shadow3aaa** [comment]
![Screenshot_2024-01-10-20-38-52-853_mark via](https://github.com/shadow3aaa/fas-rs/assets/74781933/f2dbc0cb-25d5-4007-aa71-e2c10722c1d5)
不小心点到draft了，现在已经发了
