### ISSUE TITLE
Dead cells

### ISSUE THREAD

**Issue by Byallas** [shadow3aaa/fas-rs#13]
Fas-rs doesn't see com.playdigious.deadcells.mobile, any help would be greatly appreciated 
![Screenshot_20240119-143953_X-plore](https://github.com/shadow3aaa/fas-rs/assets/157130725/dd7ddc51-3597-498c-99d3-5e0956eea27e)
![Screenshot_20240119-143935_X-plore](https://github.com/shadow3aaa/fas-rs/assets/157130725/097e618b-9917-49d7-9744-f5dbafc240c0)
:))

**Comment by nimbold** [comment]
Does deadcell support 120 fps? Or does it run at 60?

**Comment by shadow3aaa** [comment]
你尝试重启游戏了吗

**Comment by Byallas** [comment]
I tried restarting it, also I tried running it in 30, 60 and  "none" fps cap with adequate fas-fr settings, yes it runs 120 fps

Maybe the way is to set fas-fr to "none" fps cap according to how the dead cells run, I cannot set dead cells to 120 fps cap in game

**Comment by shadow3aaa** [comment]
> I tried restarting it, also I tried running it in 30, 60 and "none" fps cap with adequate fas-fr settings, yes it runs 120 fps
> 
> Maybe the way is to set fas-fr to "none" fps cap according to how the dead cells run, I cannot set dead cells to 120 fps cap in game

但是这和你设置为什么fps无关，只要注入了目标游戏就应该会记录在log内，也许你用了什么隐藏root的模块让zygisk注入失败了?

**Comment by Byallas** [comment]
Problem solved, thanks for help :))
