### ISSUE TITLE
添加一些国际服游戏?

### ISSUE THREAD

**Issue by CyanChanges** [shadow3aaa/fas-rs#14]
有一些国际服没在自带的列表上

以下应用皆在 Google Play 上
### 崩坏三
每个服有一个包名啊淦（能找到就这些了
com.miHoYo.bh3global
com.miHoYo.bh3oversea
com.miHoYo.bh3rdJP
com.miHoYo.bh3tw
com.miHoYo.bh3sea
com.miHoYo.bh3korea

### 崩坏学院2
com.miHoYo.HSoDv2JPOriginalEx

### 崩坏：星穹铁道
com.HoYoverse.hkrpgoversea

### 原神
com.miHoYo.GenshinImpact

### 还有一些其他的

com.YoStarEN.Arknights
com.YoStarJP.Arknights
tw.txwy.and.arknights

com.PigeonGames.Rizline
com.leiting.RizlineHk.android

com.YostarJP.BlueArchive
com.nexon.bluearchive
貌似ba还有好多国内/全球服的样子（

**Comment by shadow3aaa** [comment]
我想知道不让用户自己添加而不停的增长默认列表的理由是什么

**Comment by CyanChanges** [comment]
> 我想知道不让用户自己添加而不停的增长默认列表的理由是什么

这样开箱即用，方便一点（

**Comment by shadow3aaa** [comment]
主要是我不玩这些游戏，不知道它们应该是什么target_fps，如果你愿意提一个pr修改默认列表，我会合并它
