### ISSUE TITLE
最新版本启动出现报错

### ISSUE THREAD

**Issue by yzjmxy** [shadow3aaa/fas-rs#16]
[2024-02-18 13:47] INFO: Config watcher started
[2024-02-18 13:47] INFO: Cleaner thread started
[2024-02-18 13:47] ERROR: Extension loading failed, reason: RuntimeError(
    "[string \"?\"]:23: attempt to index a nil value\nstack traceback:\n\t[C]: in metamethod 'index'\n\t[string \"?\"]:23: in function 'reset'\n\t[string \"?\"]:37: in main chunk",
)
内核使用的是：https://www.coolapk1s.com/feed/53550180
项目地址：https://github.com/ztc1997/android_gki_kernel_5.10_common
根据作者推荐使用的fas-rs调度，但是似乎好像？出现了兼容性问题？

**Comment by shadow3aaa** [comment]
这是插件的错误，不是调度本身的错误，可以忽略，或者把插件卸载了

**Comment by shadow3aaa** [comment]
我看了一下帖，那个插件似乎是此内核作者的，由报错看来你应该找他反馈此问题

**Comment by yzjmxy** [comment]
> 我看了一下帖，那个插件似乎是此内核作者的，由报错看来你应该找他反馈此问题

看到酷安回复了，明白了

**Comment by shadow3aaa** [comment]
![Screenshot_2024-02-18-14-09-18-918_com.coolapk.market.jpg](https://github.com/shadow3aaa/fas-rs/assets/74781933/772046e9-71dd-4f4a-a2b6-cdcc468ca5cd)
