### ISSUE TITLE
ERROR: SerXml 

### ISSUE THREAD

**Issue by lamprose** [shadow3aaa/fas-rs#19]
之前改过一次games.toml配置 报这个错 现在还原默认games.toml依旧还是报这个错,卸载重装也没用

报错日志如下：
```[2024-03-21 17:17] INFO: Config watcher started
[2024-03-21 17:17] INFO: Cleaner thread started
[2024-03-21 17:17] ERROR: SerXml {
    source: Custom(
        "missing field `boolean`",
    ),
}
thread 'ConfigThread' panicked at src/framework/config/mod.rs:58:21:
An unrecoverable error occurred!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by shadow3aaa** [comment]
这个错误不来自games.toml，而是对scene游戏列表的序列化解析。 d221862a61b408c1e86dd56980a65aee4b1ac89d

**Comment by shadow3aaa** [comment]
> 在我这里解析正常工作…你可以提供一下`/data/data/com.omarea.vtools/shared_prefs/games.xml`这个文件吗

同时你可以提供一下scene的版本号吗，这有助于解决此问题

**Comment by lamprose** [comment]
的确是这个文件的问题  看了一下里面文件内容是```<?xml version='1.0' encoding='utf-8' standalone='yes' ?><map />```
重新生成这个文件就不报错了 scene版本号是`7.0.14`

**Comment by shadow3aaa** [comment]
> 的确是这个文件的问题  看了一下里面文件内容是```<?xml version='1.0' encoding='utf-8' standalone='yes' ?><map />```
> 重新生成这个文件就不报错了 scene版本号是`7.0.14`

所以说是因为serde序列化空map报错了🤔这倒是没想到。那么 e16d2fc32c5c4afcf6092f15a85ef6e568478d41 足以解决此问题

**Comment by shadow3aaa** [comment]
这个故事告诉我们，什么都panic只会害了你

**Comment by shadow3aaa** [comment]
PS: 这个修复得等下一次更新才会在release里面…因为我不想刷版本号。如果遇到此问题可以下载 e16d2fc32c5c4afcf6092f15a85ef6e568478d41 对应的自动构建版本即可

**Comment by lamprose** [comment]
嗯嗯  好的 谢谢大佬
