### ISSUE TITLE
在Unsupported 的设备有什么作用？

### ISSUE THREAD

**Issue by Seyud** [shadow3aaa/fas-rs#2]

**Comment by shadow3aaa** [comment]
什么意思，Unsupported就是不支持，那都用不了吧，更别说有什么作用了
还是说安装脚本出问题了unsupported也能安装了吗

**Comment by shadow3aaa** [comment]
> 什么意思，Unsupported就是不支持，那都用不了吧，更别说有什么作用了 还是说安装脚本出问题了unsupported也能安装了吗

还真是，这样nc了

**Comment by shadow3aaa** [comment]
Fix at 8822520
