### ISSUE TITLE
火影忍者一直最高频

### ISSUE THREAD

**Issue by Giask** [shadow3aaa/fas-rs#20]
![Screenshot_2024-03-26-10-00-49-57](https://github.com/shadow3aaa/fas-rs/assets/96967249/07ebaa5a-ce58-43c0-b41c-093371ff2511)
最新版fas_rs火影忍者大核和中核一直是最高频率，由于最新版fas_rs不在控制小核所以只有小核没有保持在最高频率

**Comment by shadow3aaa** [comment]
看看配置

**Comment by Giask** [comment]
> 看看配置

![Screenshot_2024-03-26-10-35-07-20.jpg](https://github.com/shadow3aaa/fas-rs/assets/96967249/257de1a1-add7-4b15-88c7-b32be21acc4b)

日志是生效的，其他游戏没有问题

**Comment by Giask** [comment]
> 看看配置

火影忍者的包名刚刚被我删了，帧率是90

**Comment by shadow3aaa** [comment]
> > 看看配置
> 
> 火影忍者的包名刚刚被我删了，帧率是90

那在下个最新ci debug构建跑一次，然后发`fas_log.txt`和scene记录长图看看

**Comment by Giask** [comment]
> > > 看看配置
> > 
> > 火影忍者的包名刚刚被我删了，帧率是90
> 
> 那在下个最新ci debug构建跑一次，然后发`fas_log.txt`和scene记录长图看看

没有，我这边只有发行版260

**Comment by Giask** [comment]
> > > > > 看看配置
> > > > 
> > > > 火影忍者的包名刚刚被我删了，帧率是90
> > > 
> > > 那在下个最新ci debug构建跑一次，然后发`fas_log.txt`和scene记录长图看看
> > 
> > 没有，我这边只有发行版260
> 
> [github action](https://github.com/shadow3aaa/fas-rs/actions/runs/8428054519)

老哥，日志文件太大了，我通过发给你的notifications@github.com邮箱

**Comment by 1140328645** [comment]
![Screenshot_2024-03-27-10-31-35-809_bin.mt.plus.jpg](https://github.com/shadow3aaa/fas-rs/assets/165120684/e806c828-8c13-4fe3-8c72-9929894115c3)

![Screenshot_2024-03-27-10-31-08-931_com.omarea.vtools.jpg](https://github.com/shadow3aaa/fas-rs/assets/165120684/2b192388-f460-4dec-bb0a-a208e8bc4f57)

这是什么问题

**Comment by 1140328645** [comment]
![Screenshot_2024-03-28-10-54-46-946_com.omarea.vtools.jpg](https://github.com/shadow3aaa/fas-rs/assets/165120684/dd907aab-68b0-48c7-9807-4c0c3dda2bbb)

不行 一直吃不满
