### ISSUE TITLE
巅峰极速不生效，之前生效的

### ISSUE THREAD

**Issue by petrichoooooo** [shadow3aaa/fas-rs#21]
![Screenshot_2024-03-30-14-55-50-59_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/shadow3aaa/fas-rs/assets/165460464/d47422aa-1e6a-4061-8fc6-3c09a5ef74d9)
![Screenshot_2024-03-30-14-56-41-72_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/shadow3aaa/fas-rs/assets/165460464/7657a7e9-75be-4dd2-addd-721096452d3f)

**Comment by shadow3aaa** [comment]
?

**Comment by petrichoooooo** [comment]
> ?

![Screenshot_2024-03-30-14-56-04-29_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/shadow3aaa/fas-rs/assets/165460464/22844a79-194d-4eda-af1f-62eb6d7d6df7)
日志没生效呀大佬，我添加了包名，其他游戏都生效了

**Comment by shadow3aaa** [comment]
> > ?
> 
> ![Screenshot_2024-03-30-14-56-04-29_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/shadow3aaa/fas-rs/assets/165460464/22844a79-194d-4eda-af1f-62eb6d7d6df7)
> 日志没生效呀大佬，我添加了包名，其他游戏都生效了

也许你要重启游戏?

**Comment by petrichoooooo** [comment]
> > > ?
> > 
> > 
> > ![Screenshot_2024-03-30-14-56-04-29_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/165460464/318175938-22844a79-194d-4eda-af1f-62eb6d7d6df7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTA0MDYsIm5iZiI6MTcxMTc5MDEwNiwicGF0aCI6Ii8xNjU0NjA0NjQvMzE4MTc1OTM4LTIyODQ0YTc5LTE5NGQtNGVkYS1hZjFmLTYyZWI2ZDdkNmRmNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwOTE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjZmZThkMDA2ZjY0OTNiOWEwNzIyMDYxYTc3NzJmZWY5ZjAxMWRmZTU2MWU3ZTE2MjY0MjBiNGI5OGU5YzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3OdrYx1CN7CR7eKmMYeg1631CDK_evJ85Ub1AhDpgg)
> > 日志没生效呀大佬，我添加了包名，其他游戏都生效了
> 
> 也许你要重启游戏?

我试了之前的版本，日志里也不生效了，应该是我的问题，但是我包名添加的应该没问题呀，请问还有什么需要注意的地方我搞错了吗大佬

**Comment by shadow3aaa** [comment]
> > > > ?
> > > 
> > > 
> > > ![Screenshot_2024-03-30-14-56-04-29_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/165460464/318175938-22844a79-194d-4eda-af1f-62eb6d7d6df7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTA0MDYsIm5iZiI6MTcxMTc5MDEwNiwicGF0aCI6Ii8xNjU0NjA0NjQvMzE4MTc1OTM4LTIyODQ0YTc5LTE5NGQtNGVkYS1hZjFmLTYyZWI2ZDdkNmRmNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwOTE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjZmZThkMDA2ZjY0OTNiOWEwNzIyMDYxYTc3NzJmZWY5ZjAxMWRmZTU2MWU3ZTE2MjY0MjBiNGI5OGU5YzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3OdrYx1CN7CR7eKmMYeg1631CDK_evJ85Ub1AhDpgg)
> > > 日志没生效呀大佬，我添加了包名，其他游戏都生效了
> > 
> > 也许你要重启游戏?
> 
> 我试了之前的版本，日志里也不生效了，应该是我的问题，但是我包名添加的应该没问题呀，请问还有什么需要注意的地方我搞错了吗大佬

可能是隐藏root的什么东西或者排除列表?它们可能会卸载zygisk，fas-rs需要一直保持注入
