### ISSUE TITLE
只要是添加到HyperOS游戏加速中的应用都会被FAS识别并处理吗？

### ISSUE THREAD

**Issue by Nep-Timeline** [shadow3aaa/fas-rs#22]
例如王者 我将其从games.toml中移除后 FAS-RS仍然会识别并处理此游戏 但是我再将其从游戏加速中移出 FAS-RS将不会识别并处理此游戏

**Comment by shadow3aaa** [comment]
不会，但是会读取scene的游戏列表

**Comment by shadow3aaa** [comment]
也许scene会读取游戏加速的列表，这我就不由得知了

**Comment by Nep-Timeline** [comment]
> 不会，但是会读取scene的游戏列表

就是这个原因，刚发现 xD
