### ISSUE TITLE
某些游戏运行频率过低(调频不积极？

### ISSUE THREAD

**Issue by ckx666ucifj** [shadow3aaa/fas-rs#26]
codm运行频率过低导致功耗过高，卡顿
![1000096295](https://github.com/shadow3aaa/fas-rs/assets/103795092/16ee61b2-6121-4ede-9f52-cf740b9499dd)
日志中有游戏包名出现
![Screenshot_2024-04-16-09-53-27-326_bin mt plus-edit](https://github.com/shadow3aaa/fas-rs/assets/103795092/f68a672a-eaf4-4831-8b02-5dc16b692230)
其他游戏正常
![1000096293](https://github.com/shadow3aaa/fas-rs/assets/103795092/57c87c25-be13-4e2c-b9db-972d1d2ee52e)
![1000096294](https://github.com/shadow3aaa/fas-rs/assets/103795092/03b8c42a-7a38-414b-aaf5-a5c163c651c5)

**Comment by ckx666ucifj** [comment]
配置
![IMG_20240416_101221](https://github.com/shadow3aaa/fas-rs/assets/103795092/814fd547-c5a1-44b6-aa7c-93201f8e6dda)

**Comment by shadow3aaa** [comment]
看起来只是温控问题，我觉得这个issue意义不大
