### ISSUE TITLE
是否有GPU监测?

### ISSUE THREAD

**Issue by mcLYX** [shadow3aaa/fas-rs#27]
某回合制游戏能把我GPU吃满，帧数下降，而CPU负载其实很少，然后fas似乎还在疯狂拉满CPU频率导致功耗暴增，撞墙，GPU频率进一步降低。感觉是没有GPU监测，如果确实没有的话可以加个，如果帧数下降但GPU占用率超过一定值(比如95%)后不再提升CPU频率

**Comment by RainGreenleaf** [comment]
fas并没有接管GPU，这种情况你可以调整fas的配置将帧率上限调低，而不是接管GPU？

**Comment by shadow3aaa** [comment]
项目是开源的，不需要通过想象来帮我补全feature

**Comment by shadow3aaa** [comment]
> 项目是开源的，不需要通过想象来帮我补全feature

答案是没有

**Comment by shadow3aaa** [comment]
如果作为新功能的话，这个功能说实话比较难实现，而且真的实现了你会发现没有什么意义，不如一开始就不开

**Comment by shadow3aaa** [comment]
> 如果作为新功能的话，这个功能说实话比较难实现，而且真的实现了你会发现没有什么意义，不如一开始就不开

比如说某6字高gpu占用游戏
