### ISSUE TITLE
[建议] 仅当正在运行fas-rs游戏列表内的游戏时才会禁用perfmgr和migt

### ISSUE THREAD

**Issue by Nep-Timeline** [shadow3aaa/fas-rs#31]
让未加入FAS-RS游戏列表内的游戏仍然使用FEAS和MIGT进行调度 如果目前就是这样 就当我没说（）

**Comment by shadow3aaa** [comment]
这不难做到，但是fas-rs不能保证关闭后它还能再开启

**Comment by Nep-Timeline** [comment]
> 这不难做到，但是fas-rs不能保证关闭后它还能再开启

FEAS吗？云控似乎会重新开启FEAS
