### ISSUE TITLE
切换游戏时模块未生效

### ISSUE THREAD

**Issue by ZXL8848** [shadow3aaa/fas-rs#37]
最开始用的是zygisk版本，测试的是和平精英
![Screenshot_2024-05-07-18-38-16-509_com omarea vtools](https://github.com/shadow3aaa/fas-rs/assets/142074151/ed2fbbb5-a397-4352-9fd1-0b75988831ad)然后再切换第五人格
![Screenshot_2024-05-09-08-16-58-822_com omarea vtools](https://github.com/shadow3aaa/fas-rs/assets/142074151/b8e5ace2-e5e1-4f33-ac55-2ed7158a3be5)
未生效，然后更换为epbf版本吊五再次启动
![Screenshot_2024-05-09-08-36-23-018_com omarea vtools](https://github.com/shadow3aaa/fas-rs/assets/142074151/9187e250-3446-40f8-a196-9e37aa0d7851)
时间有点短但是应该是生效了，再次更换和平精英
![image](https://github.com/shadow3aaa/fas-rs/assets/142074151/f0e87ddd-7ebe-4704-b6db-eb1e9e78b472)
这个和我不开fas的曲线一样，未生效，我其实测试了很多次尽量避免偶然，人后还有一个图
![image](https://github.com/shadow3aaa/fas-rs/assets/142074151/7d7b860f-238b-4136-bd76-717772e42393)
也是看完这张图我才来这儿的

**Comment by ZXL8848** [comment]
对了我手机是redmi note12Turbo澎湃系统

**Comment by shadow3aaa** [comment]
现在的最新版还有这个问题吗

**Comment by ZXL8848** [comment]
作者，你好，用了新版后没什么问题了，如果出现问题我会再反馈的
