### ISSUE TITLE
fas-rs paniced

### ISSUE THREAD

**Issue by reigadegr** [shadow3aaa/fas-rs#38]
shadow神，玩个星铁回桌面炸了
![Screenshot_2024-05-10-07-46-13-044_bin mt plus](https://github.com/shadow3aaa/fas-rs/assets/103645642/7f4d886b-75ca-4c22-837d-ab3fc2f1d884)
![Screenshot_2024-05-10-07-50-07-414_bin mt plus](https://github.com/shadow3aaa/fas-rs/assets/103645642/2b8bffab-228a-48ee-9666-b485778159e3)

**Comment by shadow3aaa** [comment]
O聚大佬试试v2.8.1
