### ISSUE TITLE
fas-rs图标

### ISSUE THREAD

**Issue by shadow3aaa** [shadow3aaa/fas-rs#42]
征集fas-rs图标一枚，用于项目logo和(开发中)的控制器应用图标

有意向者可在这个issue细说

格式最好是svg的，因为控制器是安卓应用

**Comment by shadow3aaa** [comment]
我自己画了一个，寓意帧火焰图
![Screenshot_2024-05-19-18-45-35-884_bin.mt.plus.jpg](https://github.com/shadow3aaa/fas-rs/assets/74781933/11b91699-6724-4b16-8dcf-e0948bb3c6e5)

但是它看起来不是很好:(

**Comment by yetrow** [comment]
mua🐷

**Comment by ItosEO** [comment]
不会设计

**Comment by shadow3aaa** [comment]
added in 7deab483d7b6ba92d42374225b855cec7a3f9860
