### ISSUE TITLE
关于网络调度与快速升频

### ISSUE THREAD

**Issue by Aberion** [shadow3aaa/fas-rs#45]
本人使用的是lgg8x,miui14A13,在使用fas过程中，会出现经常网络波动，具体表现为一会有网一会没网，比如打王者，有操作时延迟还算低，当没有操作时延迟蹭蹭往上，还有就是刚进游戏，就会类似于没网点几次才能进，这当然与lgg8x这部机子本身信号差有关，但是我用过其他调度，比如yc系和scene系，并且刷入了wifibonding和tcp增大模块，可能调度精细程度没有fas那么高，就没有这种情况，但是还有一个非常头疼的问题是，本人为kiwi浏览器重度使用者，在刷入fas后，经常遇到浏览器根本加载不出来的情况，就是完全不动了啊，整个页面就不动了，我使用mmc将fas默认调度调成极速把kiwi帧率调成120却没有一点效果，本人觉得在此类瞬间需要升频的应用效果没有其他调度来得直接，只是猜测但是fas好像速度要比传统调度快?本人小白，只是猜测。并且我在用thanox的压后台，但是用了fas之后，就会有一些进程莫名其妙跑出来导致cpu占用变高，正常情况下，在使用其他调度时仅仅开scene一个cpu占用显示，是只有百分之10左右的，但是fas可能在百分之20。最后就是在开发者模式中有一个增强wifi性能并省电的选项，是不是也有一部分原因，另外perapprs可以避免这种情况发生吗，个人观点仅供参考。ps:加速充电模块同理。

**Comment by shadow3aaa** [comment]
fas-rs只适用于游戏这种持续渲染场景
