### ISSUE TITLE
2.9.0 zygisk版error

### ISSUE THREAD

**Issue by Seyud** [shadow3aaa/fas-rs#49]
![Screenshot_2024-06-30-19-53-20-946_bin.mt.plus.canary.jpg](https://github.com/shadow3aaa/fas-rs/assets/97807424/6fc96b40-b8f0-43eb-9500-de94e6629615)

**Comment by shadow3aaa** [comment]
那fas-rs正常工作吗

**Comment by shadow3aaa** [comment]
Fixed in 55dd41cfc20ef9d1bd978287d6127f4585cd6016
