### ISSUE TITLE
2.9.0版本报错无法使用

### ISSUE THREAD

**Issue by Giask** [shadow3aaa/fas-rs#51]
![Screenshot_2024-07-03-18-40-48-86_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/shadow3aaa/fas-rs/assets/96967249/10a724dd-1c60-4858-8499-85b9f7133d51)

![Screenshot_2024-07-03-18-43-06-32.jpg](https://github.com/shadow3aaa/fas-rs/assets/96967249/7a5d08de-c9f0-4661-8d34-0407f93a462f)

刚开始我以为是shamiko的锅，但我把他关了还是会报错。
安卓13
骁龙870
用的zygisk版本

**Comment by shadow3aaa** [comment]
Fixed in 55dd41cfc20ef9d1bd978287d6127f4585cd6016
