### ISSUE TITLE
玩各种游戏都会突然锁帧，用的scene丧心病狂温控。两个版本都试了，144锁120锁90
天玑9200+，官核

### ISSUE THREAD

**Issue by cjlnbb666** [shadow3aaa/fas-rs#52]
![Screenshot_2024-07-09-09-46-16-494_com.topjohnwu.magisk.jpg](https://github.com/shadow3aaa/fas-rs/assets/174424788/745e9b36-9f1c-4f25-bb81-db38eaeddab2)

**Comment by shadow3aaa** [comment]
？

**Comment by hemingtsai** [comment]
？
