### ISSUE TITLE
申请适配逆水寒手游

### ISSUE THREAD

**Issue by Herobetrine** [shadow3aaa/fas-rs#56]
包名com.netease.nshm
![Screenshot_2024-07-25-08-38-48-20](https://github.com/user-attachments/assets/fcf8c1fd-fe6b-47e9-b087-977df3327203)
![Screenshot_2024-07-25-08-38-48-20](https://github.com/user-attachments/assets/dc0e3994-36fc-4cc8-bf93-1c371f57a4b6)
![Screenshot_2024-07-25-08-32-57-54](https://github.com/user-attachments/assets/783c51cd-d090-446c-b1e0-5fd18e96540e)
![Uploading Screenshot_2024-07-25-08-32-45-89.png…]()

**Comment by shadow3aaa** [comment]
找错地方了
