### ISSUE TITLE
报错无法使用

### ISSUE THREAD

**Issue by Yish1** [shadow3aaa/fas-rs#57]
zygisk和ebpf版本都试过了，均报错ERROR: Invalid argument (os error 22)
fasrs无法在原神，绝区零中工作
设备：meizu21 8gen3

![S40725-12321965_bin.mt.plus.png](https://github.com/user-attachments/assets/87b67e6c-5992-4302-979a-427403203bd1)

![S40725-12323939_m.mbq.png](https://github.com/user-attachments/assets/1314e248-bc9d-4b35-9fb4-a53e3e53ec9f)

![S40725-12321585_bin.mt.plus.png](https://github.com/user-attachments/assets/5f54e50f-0de0-4421-81ce-474a33c68159)

期待回复，感谢！

**Comment by shadow3aaa** [comment]
此报错不影响使用，在新的ci构建中已屏蔽此错误

**Comment by Yish1** [comment]
![S40725-12380307_com.omarea.vtools.png](https://github.com/user-attachments/assets/e7212339-a074-47e9-b708-0f455d5390a2)

![S40725-12375359_com.omarea.vtools.png](https://github.com/user-attachments/assets/33e6c1bf-fa7e-4f07-b5d5-e080c60c0978)

但是似乎cpu频率曲线也不太像😂
