### ISSUE TITLE
Leaks Zygisk

### ISSUE THREAD

**Issue by dotamidplayer** [shadow3aaa/fas-rs#6]
Zygisk is leaking in the latest version, already using the alpha version of shamiko and the magisk is still leaking in Momo.

**Comment by shadow3aaa** [comment]
我认为这是momo可以检测到任何要求不被unload的zygisk module引起的，然而进行任何hook后都需要禁止unload，我会考虑通过在fas server端binder返回此app不是fas应用的时候设置zygisk为可以unload的

**Comment by shadow3aaa** [comment]
但是这显然不可能解决游戏检测的问题，因为获取frametime基于注入后的hook

**Comment by dotamidplayer** [comment]
Take your time sir dont push too hard

**Comment by shadow3aaa** [comment]
66ac78c481ac78cab0df55be0e6281d01a1b4992 虽然在shamiko生效时不会被检测，但是也让注入的zygisk module不加载了，所以这个问题并没有完全解决，用户必须对目标游戏关闭shamiko hide

**Comment by shadow3aaa** [comment]
b035ebea4aa3886875a16426594dd598fe75143b 做到了目前能做到的最好情况: 开启shamiko时，非fas列表内应用不会检测到任何东西，列表内应用只能检测到zygisk

**Comment by shadow3aaa** [comment]
我认为此问题(检测到zygisk)是用户态fas hook方案无法解决的问题，如果有人认为有方法解决，可以新开一个issue
