### ISSUE TITLE
这个什么原因？？

### ISSUE THREAD

**Issue by wlisonwang** [shadow3aaa/fas-rs#60]
[2024-07-29 04:08] ERROR: DeToml(
    Error {
        inner: Error {
            inner: TomlError {
                message: "duplicate key `com.kurogame.mingchao` in table `game_list`",
                raw: Some(
                    "[config]\nkeep_std = true\nscene_game_list = true\ncontroll_min_freq = true\n\n[game_list]\n\"com.hypergryph.arknights\" = [30, 60]\n\"com.miHoYo.Yuanshen\" = [30, 60]\n\"com.miHoYo.enterprise.NGHSoD\" = [30, 60, 90]\n\"com.miHoYo.hkrpg\" = [30, 60]\n\"com.kurogame.mingchao\" = [24, 30, 45, 60]\n\"com.pwrd.hotta.laohu\" = [25, 30, 45, 60, 90]\n\"com.mojang.minecraftpe\" = [60, 90, 120]\n\"com.netease.party\" = [30, 60]\n\"com.shangyoo.neon\" = 60\n\"com.tencent.tmgp.pubgmhd\" = [60, 90, 120]\n\"com.tencent.tmgp.sgame\" = [30, 60, 90, 120]\n\"com.kurogame.mingchao\" = [30, 60]\n\"com.miHoYo.Nap\" = [30, 60]\n\"com.tencent.lolm\" = [30, 60, 90, 120]\n\"com.tencent.jkchess\" = [30, 60, 90, 120]\n\n\n[powersave]\nmargin = 4\n\n[balance]\nmargin = 3\n\n[performance]\nmargin = 2\n\n[fast]\nmargin = 1\n",
                ),
                keys: [],
                span: Some(
                    507..508,
                ),
            },
        },
    },
)

**Comment by shadow3aaa** [comment]
重复键
