### ISSUE TITLE
[建议]增加一个手动开启fas的选项

### ISSUE THREAD

**Issue by Sharl210** [shadow3aaa/fas-rs#61]
有时候fas关闭以后，比如说游戏回到后台，但是放后台挂一会儿，或者说某些情况下，它掉了，下次再打开游戏，它并不会自动开启，这个时候就只能划掉游戏的后台，重新进游戏，而且这个情况也不清楚是什么原因，我这边复现也是有时候能复现，有时候不能复现，把系统的调度和很多有相关冲突的全部都关了，还是会出现，所以希望能下次出现这种它没有自动加载的情况时，能够手动开启，目前只做了一个有小窗时关闭fas

**Comment by Kissycat** [comment]
倒是不用划掉吧，打开小窗再关闭小窗应该就可以了

**Comment by Sharl210** [comment]
> 倒是不用划掉吧，打开小窗再关闭小窗应该就可以了

不是，事实上，我打开小窗fas都并不会关闭😂，不是有插件吗，他提供了一个stop_fas()的回调函数，我这边开小窗没任何反应，只有退游戏才停止，OnePlus Ace2pro Coloros14

**Comment by shadow3aaa** [comment]
> > 倒是不用划掉吧，打开小窗再关闭小窗应该就可以了
> 
> 不是，事实上，我打开小窗fas都并不会关闭😂，不是有插件吗，他提供了一个stop_fas()的回调函数，我这边开小窗没任何反应，只有退游戏才停止，OnePlus Ace2pro Coloros14

小窗检测好像在一加有点问题，必须焦点在小窗才触发

**Comment by shadow3aaa** [comment]
> > 倒是不用划掉吧，打开小窗再关闭小窗应该就可以了
> 
> 不是，事实上，我打开小窗fas都并不会关闭😂，不是有插件吗，他提供了一个stop_fas()的回调函数，我这边开小窗没任何反应，只有退游戏才停止，OnePlus Ace2pro Coloros14

小窗检测好像在一加有点问题，必须焦点在小窗才触发

**Comment by Sharl210** [comment]
> > > 倒是不用划掉吧，打开小窗再关闭小窗应该就可以了
> > 
> > 不是，事实上，我打开小窗fas都并不会关闭😂，不是有插件吗，他提供了一个stop_fas()的回调函数，我这边开小窗没任何反应，只有退游戏才停止，OnePlus Ace2pro Coloros14
> 
> 小窗检测好像在一加有点问题，必须焦点在小窗才触发

没有焦点，我也试了，不管是游戏内其他应用小窗还是其他应用内游戏改成小窗，焦点在哪里，他都没有任何反应，关键是有小窗，他还不会停，其他时候有时候我把游戏挂在后台一会或者说一晚上然后再重进游戏，它就不会自己开启了，而且这个状态掉的很频繁，但是也不知道到底是什么原因导致的

**Comment by Sharl210** [comment]
> > > > 倒是不用划掉吧，打开小窗再关闭小窗应该就可以了
> > > 
> > > 不是，事实上，我打开小窗fas都并不会关闭😂，不是有插件吗，他提供了一个stop_fas()的回调函数，我这边开小窗没任何反应，只有退游戏才停止，OnePlus Ace2pro Coloros14
> > 
> > 小窗检测好像在一加有点问题，必须焦点在小窗才触发
> 
> 我也试了，不管是游戏内其他应用小窗还是其他应用内游戏改成小窗，焦点在哪里，他都没有任何反应，关键是有小窗，他还不会停，其他时候有时候我把游戏挂在后台一会或者说一晚上然后再重进游戏，它就不会自己开启了，而且这个状态掉的很频繁，但是也不知道到底是什么原因导致的

好吧，焦点在小窗内，确实好像可以停，但是我这边日志刷的太快了，所以我没注意到，确实停了，然后切回来就好了，但是还是一样的，把游戏挂后台挂久了，它就自己掉了这个状态，然后之后再回到游戏，它也不会有任何反应，整一个就完全没反应了，只有把后台划掉，重进游戏才会重新检测

**Comment by Kissycat** [comment]
好吧，我这里MIUI打几个小时也会掉一两次，但是打开小窗一切换就又回来了..
