### ISSUE TITLE
MIUI官核天玑9200+用的ebpf，刷了最新版的asoul模式2关闭了核心分配，3.1.0死活吃不上但日志显示正常，3.0.1就没事

### ISSUE THREAD

**Issue by cjlnbb666** [shadow3aaa/fas-rs#64]
![Screenshot_2024-08-06-03-26-07-507_com.omarea.vtools.jpg](https://github.com/user-attachments/assets/c008ca3d-f836-4388-ac4f-132d5365f8ca)

![Screenshot_2024-08-06-03-42-05-863_com.topjohnwu.magisk.jpg](https://github.com/user-attachments/assets/805cfb35-c6d9-46f2-8b3d-e915987b227d)

![Screenshot_2024-08-06-03-36-03-489_com.omarea.vtools.jpg](https://github.com/user-attachments/assets/5817d738-43b7-4b21-ae63-7b5b6804984c)

**Comment by Kissycat** [comment]
它其实生效了，只是长得和以前不一样了..

**Comment by cjlnbb666** [comment]
> 它其实生效了，只是长得和以前不一样了..

啊这，公告居然不说……

**Comment by hemingtsai** [comment]
> > 它其实生效了，只是长得和以前不一样了..
> 
> 啊这，公告居然不说……

用别人写的开源软件起码要关注wiki和其他动向吧，，，，，

**Comment by cjlnbb666** [comment]
> > > 它其实生效了，只是长得和以前不一样了..
> > 
> > 啊这，公告居然不说……
> 
> 用别人写的开源软件起码要关注wiki和其他动向吧，，，，，
> 

确实
