### ISSUE TITLE
对于双大核soc仅调用一个大核心

### ISSUE THREAD

**Issue by adjjj** [shadow3aaa/fas-rs#66]
设备：tb-j607f
soc：高通骁龙750g，搭载2xA77+6xA55
安卓12
游戏为碧蓝档案国际服
fas-rs运行过程中，仅调用了一个A77核心，占用维持在90左右，另一A77核心占用仅为40
fas-rs在mtk8100平台运行效果极好，与sd750g平台形成反差

**Comment by shadow3aaa** [comment]
fas-rs目前不处理线程放置
