### ISSUE TITLE
编译出错，这个是什么情况

### ISSUE THREAD

**Issue by ucxl** [shadow3aaa/fas-rs#70]
Compiling mlua v0.9.9
error: failed to run custom build command for `frame-analyzer v0.2.6`

Caused by:
  process didn't exit successfully: `/root/fas-rs/target/release/build/frame-analyzer-44fbbd212ed5d3e2/build-script-build` (exit status: 1)
  --- stderr
      Updating crates.io index
    Installing bpf-linker v0.9.13
      Updating crates.io index
       Locking 95 packages to latest compatible versions
        Adding matchers v0.1.0 (latest: v0.2.0)
        Adding nu-ansi-term v0.46.0 (latest: v0.50.1)
        Adding regex-automata v0.1.10 (latest: v0.4.7)
        Adding regex-syntax v0.6.29 (latest: v0.8.4)
        Adding windows-sys v0.52.0 (latest: v0.59.0)
     Compiling proc-macro2 v1.0.86
     Compiling unicode-ident v1.0.12
     Compiling serde v1.0.210
     Compiling anyhow v1.0.87
     Compiling thiserror v1.0.63
     Compiling semver v1.0.23
     Compiling once_cell v1.19.0
     Compiling serde_json v1.0.128
     Compiling quote v1.0.37
     Compiling camino v1.1.9
     Compiling cfg-if v1.0.0
     Compiling syn v2.0.77
     Compiling shlex v1.3.0
     Compiling tracing-core v0.1.32
     Compiling cc v1.1.18
     Compiling lazy_static v1.5.0
     Compiling regex-lite v0.1.6
     Compiling ryu v1.0.18
     Compiling rustversion v1.0.17
     Compiling memchr v2.7.4
     Compiling itoa v1.0.11
     Compiling regex-syntax v0.6.29
     Compiling prettyplease v0.2.22
     Compiling regex-syntax v0.8.4
     Compiling log v0.4.22
     Compiling utf8parse v0.2.2
     Compiling libc v0.2.158
     Compiling pin-project-lite v0.2.14
     Compiling crossbeam-utils v0.8.20
     Compiling overload v0.1.1
     Compiling nu-ansi-term v0.46.0
     Compiling anstyle-parse v0.2.5
     Compiling sharded-slab v0.1.7
     Compiling regex-automata v0.1.10
     Compiling tracing-log v0.2.0
     Compiling thread_local v1.1.8
     Compiling regex-automata v0.4.7
     Compiling is_terminal_polyfill v1.70.1
     Compiling matchers v0.1.0
     Compiling anstyle-query v1.1.1
     Compiling powerfmt v0.2.0
     Compiling colorchoice v1.0.2
     Compiling anstyle v1.0.8
     Compiling smallvec v1.13.2
     Compiling anstream v0.6.15
     Compiling deranged v0.3.11
     Compiling regex v1.10.6
     Compiling clap_lex v0.7.2
     Compiling hashbrown v0.14.5
     Compiling serde_derive v1.0.210
     Compiling thiserror-impl v1.0.63
     Compiling tracing-attributes v0.1.27
     Compiling strsim v0.11.1
     Compiling time-core v0.1.2
     Compiling equivalent v1.0.1
     Compiling tracing v0.1.40
     Compiling heck v0.5.0
     Compiling num-conv v0.1.0
     Compiling tracing-subscriber v0.3.18
     Compiling clap_derive v4.5.13
     Compiling time v0.3.36
     Compiling indexmap v2.5.0
     Compiling clap_builder v4.5.17
     Compiling crossbeam-channel v0.5.13
     Compiling libloading v0.8.5
     Compiling stable_deref_trait v1.2.0
     Compiling fallible-iterator v0.3.0
     Compiling nu-ansi-term v0.50.1
     Compiling gimli v0.31.0
     Compiling tracing-tree v0.4.0
     Compiling clap v4.5.17
     Compiling llvm-sys v191.0.0-rc1
     Compiling cargo-platform v0.1.8
     Compiling tracing-appender v0.2.3
     Compiling cargo_metadata v0.18.1
     Compiling ar v0.9.0
     Compiling aya-rustc-llvm-proxy v0.9.3
     Compiling bpf-linker v0.9.13
      Finished `release` profile [optimized + debuginfo] target(s) in 2m 33s
    Installing /root/fas-rs/target/aarch64-linux-android/release/build/frame-analyzer-685470e56556a8e9/out/temp_target/bin/bpf-linker
     Installed package `bpf-linker v0.9.13` (executable `bpf-linker`)
  warning: be sure to add `/root/fas-rs/target/aarch64-linux-android/release/build/frame-analyzer-685470e56556a8e9/out/temp_target/bin` to your PATH to be able to run the installed binaries
  error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
  Error: No such file or directory (os error 2)
note: If the build failed due to a missing target, you can run this command:
note: 
note:     rustup target install aarch64-linux-android
Traceback (most recent call last):
  File "/root/fas-rs/./make.py", line 51, in <module>
    build.task(sys.argv[2:])
  File "/root/fas-rs/maketools/build.py", line 146, in task
    cargo.build()
  File "/root/fas-rs/maketools/toolchains.py", line 76, in build
    raise Exception("Rust build failed!")
Exception: Rust build failed!

**Comment by shadow3aaa** [comment]
看起来是bpf-linker没有成功找到并调用，最后解决了吗
