### ISSUE TITLE
Provide build instruction on Darwin/macOS

### ISSUE THREAD

**Issue by Xerxes-2** [shadow3aaa/fas-rs#75]
I cannot compile this repo out of box on macOS. Is it possible to cross compile it?

Additionally, would you please write a contribution guide on how to contribute to `fas-rs`?

**Comment by shadow3aaa** [comment]
> I cannot compile this repo out of box on macOS. Is it possible to cross compile it?
> 
> Additionally, would you please write a contribution guide on how to contribute to `fas-rs`?

I will consider it, thank you.

**Comment by shadow3aaa** [comment]
> I cannot compile this repo out of box on macOS. Is it possible to cross compile it?
> 
> Additionally, would you please write a contribution guide on how to contribute to `fas-rs`?

[CONTRIBUTING.md](https://github.com/shadow3aaa/fas-rs/blob/master/CONTRIBUTING.md) is added in f61bb1b266869d329f15bdc04d050bbc5866860c.
