### ISSUE TITLE
启用fas-rs后 红魔8pro（普通版高通8GEN2）超大核频率被限制为2956MHz

### ISSUE THREAD

**Issue by yutouyes** [shadow3aaa/fas-rs#8]
![Screenshot_20231005_021252.jpg](https://github.com/shadow3aaa/fas-rs/assets/17039457/a969698f-bced-4c0a-9052-8873a34ebbd6)

禁用fas-rs后可工作于最大频率3187MHz
![Screenshot_原神_20231005_014547.jpg](https://github.com/shadow3aaa/fas-rs/assets/17039457/570e3ab6-f83a-4c38-893d-3698031dd561)

系统为红魔8.0，安卓13，原厂内核与Pandora beta10内核均有相同情况

**Comment by yutouyes** [comment]
已尝试过移出或移入游戏助手，没有变化

**Comment by yutouyes** [comment]
已尝试删除所有温控，游戏助手调度测试已失效，在不启用fas-rs时超大核最高可以达到3187MHz，但启用fas-rs后仍限制在2956MHz，请问这个是有意的设置还是预期之外的情况？是否有调整的地方

**Comment by shadow3aaa** [comment]
Meaning less

**Comment by Herobetrine** [comment]
测试结果显示8g3在3052mhz之上的频率性能提升很小而电量消耗很大，即能效比拉跨，所以直接禁用了
